// ItemList
export const GET_ITEMS = "GET_ITEMS";
export const GET_MORE_ITEMS = "GET_MORE_ITEMS";
export const SERVER_ERROR = "SERVER_ERROR";
export const LOADING_ITEMS = "LOADING_ITEMS";

// Product Cart
export const OPEN_CART_MODAL = "OPEN_CART_MODAL";
export const CLOSE_CART_MODAL = "CLOSE_CART_MODAL";
export const SEND_CART_FORM = "SEND_CART_FORM";
export const SEND_CART_FORM_WAITING = "SEND_CART_FORM_WAITING";
export const PREPARE_TO_BUY = "PREPARE_TO_BUY";

// Product Item
export const OPEN_PRODUCT_ITEM_MODAL = "OPEN_PRODUCT_ITEM_MODAL";
export const CLOSE_PRODUCT_ITEM_MODAL = "CLOSE_PRODUCT_ITEM_MODAL";
export const SEND_PRODUCT_ITEM_TO_CART = "SEND_PRODUCT_ITEM_TO_CART";

// Setiings
export const OPEN_SETTINGS_MODAL = "OPEN_SETTINGS_MODAL";
export const CHANGE_CURRENCY = "CHANGE_CURRENCY";
export const CLOSE_SETTINGS_MODAL = "CLOSE_SETTINGS_MODAL";
export const GET_EXCHANGE_RATES = "GET_EXCHANGE_RATES";
export const GET_EXCHANGE_RATES_WAITING = "GET_EXCHANGE_RATES_WAITING";
