// ItemList
export const GET_MORE_ITEMS = "GET_MORE_ITEMS";
export const SERVER_ERROR = "SERVER_ERROR";
export const LOADING_ITEMS = "LOADING_ITEMS";

// Shopping Cart
export const CLOSE_CART_MODAL = "CLOSE_CART_MODAL";
export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
export const SEND_CART_FORM = "SEND_CART_FORM";
export const SEND_CART_FORM_WAITING = "SEND_CART_FORM_WAITING";
export const PREPARE_TO_BUY = "PREPARE_TO_BUY";

// Product Item
export const OPEN_PRODUCT_ITEM_MODAL = "OPEN_PRODUCT_ITEM_MODAL";
export const GET_PRODUCT_ITEM_FULL_DESCRIPTION = "GET_PRODUCT_ITEM_FULL_DESCRIPTION";

// Settings
export const OPEN_SETTINGS_MODAL = "OPEN_SETTINGS_MODAL";
export const CLOSE_SETTINGS_MODAL = "CLOSE_SETTINGS_MODAL";
export const FULLSCREEN_MODE = "FULLSCREEN_MODE";

// Transitions
export const OPEN_AUTH_PAGE = "OPEN_AUTH_PAGE";
export const CLOSE_AUTH_PAGE = "CLOSE_AUTH_PAGE";
export const CHANGE_CONTENT_PAGE = "CHANGE_CONTENT_PAGE";
export const TRANSITION_END = "TRANSITION_END";

// admin
export const ADMIN_GET_PRODUCT_ITEM_AVAILABLE_CATEGORIES = "ADMIN_GET_PRODUCT_ITEM_AVAILABLE_CATEGORIES";
export const ADMIN_GET_PRODUCT_ITEM_AVAILABLE_CATEGORIES_WAITING = "ADMIN_GET_PRODUCT_ITEM_AVAILABLE_CATEGORIES_WAITING";
export const ADMIN_PRODUCT_ITEM_CREATE = "ADMIN_PRODUCT_ITEM_CREATE";
export const ADMIN_PRODUCT_ITEM_CREATE_WAITING = "ADMIN_PRODUCT_ITEM_CREATE_WAITING";
export const ADMIN_UPDATE_EXCHANGE_RATES = "ADMIN_UPDATE_EXCHANGE_RATES";
export const ADMIN_UPDATE_EXCHANGE_RATES_WAITING = "ADMIN_UPDATE_EXCHANGE_RATES_WAITING";
export const ADMIN_GET_EXCHANGE_RATES = "ADMIN_GET_EXCHANGE_RATES";
export const ADMIN_GET_EXCHANGE_RATES_WAITING = "ADMIN_GET_EXCHANGE_RATES_WAITING";
